logging:
  path: logs
  file: ${logging.path}/myapplication.log
  level:
    root: WARN
    org.springframework.web: ERROR
    com.ingeniance: TRACE
    org.hibernate: ERROR
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"