version: '3.3'

services:
  api:
    image: 'employeeapiavecpostgres'
    ports: 
        - 2369:9000
    build:
      context: .
    container_name: api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks: 
      - wp
          
  webapp:
    image: 'employeewebapp'
    ports: 
        - 2370:9001
    restart: always
    build:
      context: .
    container_name: webapp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks: 
      - wp

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks: 
      - wp

networks:
  wp:
volumes:
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/employeebd/db
  wp_statics:
     driver: local
     driver_opts:
      o: bind
      type: none
      device: srv/employeebd/statics 
