node {
 
    def buildNum = env.BUILD_NUMBER 
    def branchName= env.BRANCH_NAME
    def image
    
    print buildNum
    print branchName

    //def registryCredential = 'dockerhub'
    //def registry = 'https://hub.docker.com/repository/docker/rliance/mondockerrepo'
    //def IMAGE="rliance/mondockerrepo:version-${env.BUILD_ID}"
    	
   stage('Clone') {
        git 'https://github.com/remiliance/projetAPI_EmployeeController.git'
   }

   dir('api') {
   stage('Build Maven') {
        echo 'debut du build'
        sh 'mvn package -Dmaven.test.skip=true' 
    
    }
	   
   stage('Build Docker Image') {
         image = docker.build("api_employee/myapp","MyAwesomeApp")
    }

    stage('Push') {
	    withDockerRegistry([credentialsId: "dockerhub", url: "https;://inde.docker.io/v1/"]){
	    image.push()
      }   
      sh "docker rmi $imageName:${buildNum}"
    }
   }
}
